/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAisRouteImport } from './routes/api/ais'
import { Route as ApiGfwRouteImport } from './routes/api/gfw'
import { Route as ApiSarRouteImport } from './routes/api/sar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAisRoute = ApiAisRouteImport.update({
  id: '/api/ais',
  path: '/api/ais',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGfwRoute = ApiGfwRouteImport.update({
  id: '/api/gfw',
  path: '/api/gfw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSarRoute = ApiSarRouteImport.update({
  id: '/api/sar',
  path: '/api/sar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ais': typeof ApiAisRoute
  '/api/gfw': typeof ApiGfwRoute
  '/api/sar': typeof ApiSarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ais': typeof ApiAisRoute
  '/api/gfw': typeof ApiGfwRoute
  '/api/sar': typeof ApiSarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ais': typeof ApiAisRoute
  '/api/gfw': typeof ApiGfwRoute
  '/api/sar': typeof ApiSarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ais' | '/api/gfw' | '/api/sar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ais' | '/api/gfw' | '/api/sar'
  id: '__root__' | '/' | '/api/ais' | '/api/gfw' | '/api/sar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAisRoute: typeof ApiAisRoute
  ApiGfwRoute: typeof ApiGfwRoute
  ApiSarRoute: typeof ApiSarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ais': {
      id: '/api/ais'
      path: '/api/ais'
      fullPath: '/api/ais'
      preLoaderRoute: typeof ApiAisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gfw': {
      id: '/api/gfw'
      path: '/api/gfw'
      fullPath: '/api/gfw'
      preLoaderRoute: typeof ApiGfwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sar': {
      id: '/api/sar'
      path: '/api/sar'
      fullPath: '/api/sar'
      preLoaderRoute: typeof ApiSarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAisRoute: ApiAisRoute,
  ApiGfwRoute: ApiGfwRoute,
  ApiSarRoute: ApiSarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
